ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
theme = "hugo-theme-slim"
baseURL = "https://example.com/"
languageCode = "en-us"
title = "Kaitlyn Brewer's Blog"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[Params]
  math = false
  summary = true
  disqusShortname = ""
  
  # social
  GithubID = ""
  TwitterID = ""
  LinkedInID = ""
  
[[menu.main]]
  name = "About"
  URL = "/about/"

[[menu.main]]
  name = "Tags"
  URL = "/tags/"
  
[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
    
    