ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
relativeurls = true
theme = "hugo-theme-slim"
baseURL = "https://example.com/"
languageCode = "en-us"
title = "Slim Theme Demo"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[Params]
  math = false
  summary = true
  disqusShortname = ""
  
  # social
  GithubID = ""
  TwitterID = ""
  LinkedInID = ""
  
[[menu.main]]
  name = "About"
  URL = "/about/"